description: 'WeOptimize.ai - Testing'
prompts:
  - file://../../prompts/conversation_prompts.json

providers:
  - file://../api-config/weoptimize-ai.yaml

tests:
  - file://../../tests/conversation_asserts.yaml
